### ISSUE TITLE
Public access problem 

### ISSUE THREAD

**Issue by shahbazsyed** [tl74dylo/Winesearch#2]
Getting the following error when running `sudo mvn clean install`

`[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/vija1705/irprojects/wine-search/Winesearch-master/winesearch/src/main/java/servlet/IndexServlet.java:[64,27] indexCSV(org.apache.lucene.index.IndexWriter) is not public in com.winesearch.maven.winesearch.IndexFiles; cannot be accessed from outside package`

**Comment by tl74dylo** [comment]
Added the public setting, should work now.
If you encounter any other problem, please let us know.
